# Generated by Django 5.0 on 2026-09-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_adminbankaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminQrisSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='QRIS Pembayaran Official', max_length=100)),
                ('qris_image', models.ImageField(upload_to='qris_images/')),
                ('notes', models.TextField(blank=True, help_text='Catatan atau petunjuk pembayaran QRIS', null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('QRIS', 'QRIS'), ('GATEWAY', 'Payment Gateway (Midtrans/Qris/etc)')], default='CASH', max_length=30),
        ),
    ]
