from django.urls import path
from getskills import getskills_views
from users import users_views
app_name='getskills'
urlpatterns = [

	path('users/',users_views.users,name="users"),
	path('user-details/<int:id>/',users_views.user_details,name="user-details"),
	path('add-user/',users_views.add_user,name="add-user"),
	path('edit-user/<int:id>/',users_views.edit_user,name="edit-user"),
	path('delete-user/<int:id>/',users_views.delete_user,name="delete-user"),
	path('delete-multiple-user/',users_views.delete_multiple_user,name="delete-multiple-user"),

	path('login/',users_views.login_user,name="login"),
	path('logout/',users_views.logout_user,name="logout"),
	path('groups/',users_views.groups_list,name="groups"),
	path('group-edit/<int:id>/',users_views.group_edit,name="group-edit"),
	path('group-delete/<int:id>/',users_views.group_delete,name="group-delete"),
	path('group-add/',users_views.group_add,name="group-add"),
	path('permissions/',users_views.permissions,name="permissions"),
	path('edit-permissions/<int:id>/',users_views.edit_permissions,name="edit-permissions"),
	path('delete-permissions/<int:id>/',users_views.delete_permissions,name="delete-permissions"),
	path('assign-permissions-to-user/<int:id>/',users_views.assign_permissions_to_user,name="assign-permissions-to-user"),
	path('signup/',users_views.signup,name="signup"),
	path('activate/<uidb64>/<token>/',users_views.activate, name='activate'),

    path('',getskills_views.index,name="index"),
    path('index/',getskills_views.index,name="index"),
    path('index-2/',getskills_views.index2,name="index-2"),
    path('schedule/',getskills_views.schedule,name="schedule"),
    path('instructors/',getskills_views.instructors,name="instructors"),
    path('message/',getskills_views.message,name="message"),
    path('activity/',getskills_views.activity,name="activity"),
    path('profile/',getskills_views.profile,name="profile"),
    path('courses/',getskills_views.courses,name="courses"),
    path('course-details-1/',getskills_views.course_details_1,name="course-details-1"),
    path('course-details-2/',getskills_views.course_details_2,name="course-details-2"),
    path('instructor-dashboard/',getskills_views.instructor_dashboard,name="instructor-dashboard"),
    path('instructor-courses/',getskills_views.instructor_courses,name="instructor-courses"),
    path('instructor-schedule/',getskills_views.instructor_schedule,name="instructor-schedule"),
    path('instructor-students/',getskills_views.instructor_students,name="instructor-students"),
    path('instructor-resources/',getskills_views.instructor_resources,name="instructor-resources"),
    path('instructor-transactions/',getskills_views.instructor_transactions,name="instructor-transactions"),
    path('instructor-liveclass/',getskills_views.instructor_liveclass,name="instructor-liveclass"),
    path('app-profile/',getskills_views.app_profile,name="app-profile"),
    path('post-details/',getskills_views.post_details,name="post-details"),
    path('email-compose/',getskills_views.email_compose,name="email-compose"),
    path('email-inbox/',getskills_views.email_inbox,name="email-inbox"),
    path('email-read/',getskills_views.email_read,name="email-read"),
    path('app-calender/',getskills_views.app_calender,name="app-calender"),
    path('ecom-product-grid/',getskills_views.ecom_product_grid,name="ecom-product-grid"),
    path('ecom-product-list/',getskills_views.ecom_product_list,name="ecom-product-list"),
    path('ecom-product-detail/',getskills_views.ecom_product_detail,name="ecom-product-detail"),
    path('ecom-product-order/',getskills_views.ecom_product_order,name="ecom-product-order"),
    path('ecom-checkout/',getskills_views.ecom_checkout,name="ecom-checkout"),
    path('ecom-invoice/',getskills_views.ecom_invoice,name="ecom-invoice"),
    path('ecom-customers/',getskills_views.ecom_customers,name="ecom-customers"),
    path('chart-flot/',getskills_views.chart_flot,name="chart-flot"),
    path('chart-morris/',getskills_views.chart_morris,name="chart-morris"),
    path('chart-chartjs/',getskills_views.chart_chartjs,name="chart-chartjs"),
    path('chart-chartist/',getskills_views.chart_chartist,name="chart-chartist"),
    path('chart-sparkline/',getskills_views.chart_sparkline,name="chart-sparkline"),
    path('chart-peity/',getskills_views.chart_peity,name="chart-peity"),

    path('ui-accordion/',getskills_views.ui_accordion,name="ui-accordion"),
    path('ui-alert/',getskills_views.ui_alert,name="ui-alert"),
    path('ui-badge/',getskills_views.ui_badge,name="ui-badge"),
    path('ui-button/',getskills_views.ui_button,name="ui-button"),
    path('ui-modal/',getskills_views.ui_modal,name="ui-modal"),
    path('ui-button-group/',getskills_views.ui_button_group,name="ui-button-group"),
    path('ui-list-group/',getskills_views.ui_list_group,name="ui-list-group"),
    path('ui-media-object/',getskills_views.ui_media_object,name="ui-media-object"),
    path('ui-card/',getskills_views.ui_card,name="ui-card"),
    path('ui-carousel/',getskills_views.ui_carousel,name="ui-carousel"),
    path('ui-dropdown/',getskills_views.ui_dropdown,name="ui-dropdown"),
    path('ui-popover/',getskills_views.ui_popover,name="ui-popover"),
    path('ui-progressbar/',getskills_views.ui_progressbar,name="ui-progressbar"),
    path('ui-tab/',getskills_views.ui_tab,name="ui-tab"),
    path('ui-typography/',getskills_views.ui_typography,name="ui-typography"),
    path('ui-pagination/',getskills_views.ui_pagination,name="ui-pagination"),
    path('ui-grid/',getskills_views.ui_grid,name="ui-grid"),

    path('uc-select2/',getskills_views.uc_select2,name="uc-select2"),
    path('uc-nestable/',getskills_views.uc_nestable,name="uc-nestable"),
    path('uc-noui-slider/',getskills_views.uc_noui_slider,name="uc-noui-slider"),
    path('uc-sweetalert/',getskills_views.uc_sweetalert,name="uc-sweetalert"),
    path('uc-toastr/',getskills_views.uc_toastr,name="uc-toastr"),
    path('map-jqvmap/',getskills_views.map_jqvmap,name="map-jqvmap"),
    path('uc-lightgallery/',getskills_views.uc_lightgallery,name="uc-lightgallery"),
    path('uc-lightgallery/',getskills_views.uc_lightgallery,name="uc-lightgallery"),
    path('widget-basic/',getskills_views.widget_basic,name="widget-basic"),

    path('form-element/',getskills_views.form_element,name="form-element"),
    path('form-wizard/',getskills_views.form_wizard,name="form-wizard"),
    path('form-ckeditor/',getskills_views.form_ckeditor,name="form-ckeditor"),
    path('form-pickers/',getskills_views.form_pickers,name="form-pickers"),
    path('form-validation/',getskills_views.form_validation,name="form-validation"),

    path('table-bootstrap-basic/',getskills_views.table_bootstrap_basic,name="table-bootstrap-basic"),
    path('table-datatable-basic/',getskills_views.table_datatable_basic,name="table-datatable-basic"),

    path('page-lock-screen/',getskills_views.page_lock_screen,name="page-lock-screen"),
    path('page-error-400/',getskills_views.page_error_400,name="page-error-400"),
    path('page-error-403/',getskills_views.page_error_403,name="page-error-403"),
    path('page-error-404/',getskills_views.page_error_404,name="page-error-404"),
    path('page-error-500/',getskills_views.page_error_500,name="page-error-500"),
    path('page-error-503/',getskills_views.page_error_503,name="page-error-503"),
    path('empty-page/',getskills_views.empty_page,name="empty-page"),

]